### ISSUE TITLE
recommended Fasta file

### ISSUE THREAD

**Issue by ShirAmit96** [YY-TMU/InPACT#10]
Hi,

I executed the following command:

"InPACT -i sample.bam -a hg38.109.20211119.ncbiRefSeq.gtf -s InPACT_polyAsites.hg38.saf -P 5"
This produced the file 1.predicted.terminal.results.txt in the output folder.

Is this the only output that I should expect?

Additionally, I attempted to run the following command, but it didn’t generate any final output:

"InPACT_transcript --predict_terminal 1.predicted.terminal.results.txt --annotated_gtf hg38.109.20211119.ncbiRefSeq.gtf --fa_path GRCh38.d1.vd1.fa --save_gtf merged.gtf"
Could the issue be related to the FASTA file? What is the correct FASTA file that I should be using?

Thanks!

**Comment by liuxc1995** [comment]
Hi, 

Thank you for your question.

For the first question, the file `1.predicted.terminal.results.txt` is the primary output generated from the command.
[](url)
For the second question, using the [FASTA](https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz) file from UCSC  should work for `InPACT_transcript `.

**Comment by Hrision** [comment]
Hello!
I would like to inquire where I should get this file (InPACT_polyAsites.hg38.saf) in this code (InPACT -i sample.bam -a RefSeq.gtf -s InPACT_polyAsites.hg38.saf -P 5)?

**Comment by Hrision** [comment]
Well, after careful reading I found that file and started on the next step. Thanks a lot.
