### ISSUE TITLE
IPA ref for other models

### ISSUE THREAD

**Issue by Toutouflipi** [YY-TMU/InPACT#3]
Hi! Thank you for this great software. 

I was wondering if you plan to include other models or a code for building the necessary IPA reference?
I work with danio rerio and would love to use InPACT!

Thanks!

**Comment by liuxc1995** [comment]
Hello! Thank you for your interest in InPACT!

While our current focus is on human data, we are definitely open to expanding InPACT to support other species, such as Danio rerio. We appreciate your suggestion and will keep you informed of any developments regarding the inclusion of Danio rerio in InPACT.

Liu

**Comment by Toutouflipi** [comment]
Thank you very much! 

I am looking forward to it!
