### ISSUE TITLE
Input file format question

### ISSUE THREAD

**Issue by cloudyrainy-zh** [YY-TMU/InPACT#4]
Hello! Thank you for this exciting software. 

I would like to ask the author about the input files being limited to the BAM format, I am using two public datasets from GEO (GSE131179 and GSE120649) and both of them can only be fulfilled by converting from SRA format to BAM format, but both of them give me an error when I run them, prompting me to make sure that I am typing in the correct BAM or SAM format file!

Also regarding the test file you mentioned, I downloaded it and found that it is also an SRA file, do I also have to convert it to BAM to run it further?

Thanks a lot！

**Comment by liuxc1995** [comment]
Hello! Thank you for your interest in InPACT and your inquiries about input file formats.

InPACT is designed to process BAM files as its primary input format. Regarding the test data, which was originally provided in SRA format, it is imperative to convert it into FASTQ format and subsequently align it to the GRCh38 reference genome to generate a compatible BAM file for use with InPACT.

Thank you,
Liu

**Comment by cloudyrainy-zh** [comment]
Thanks for your quick response.
