### ISSUE TITLE
getopt illegal option --o

### ISSUE THREAD

**Issue by tailana703** [YY-TMU/InPACT#7]
Hello,

I really would like to use your software on one of the datasets. Can it run on MacOS? I installed it successfully, but when I call InPACT -h
the error 'getopt illegal option --o' kept popping up. I tried to remove -o from the 'InPACT' script, but now I get another error:
error: argument --annotation_file: expected one argument 
although I'm sure that I put only one argument after -a in InPACT call.

Any suggestions?

**Comment by liuxc1995** [comment]
Hello!

Thank you for raising this issue. The `getopt` command under MacOS defaults to the FreeBSD version, which is different from the GNU/Linux version. To resolve this, you can install the GNU version of getopt and specify its path in script. Here’s how you can do it:

1. Install GNU getopt using Homebrew

```
brew install gnu-getopt
```

2. Specify the path of GNU getopt in script

```
#!/bin/bash 

GETOPT=/xxx/bin/getopt 
ARGS=`$GETOPT XXX`
```

We hope this helps you resolve the issue. If it doesn't work, we recommend running it on Linux. If you have any further questions, feel free to ask.

Thank you,
Liu
