### ISSUE TITLE
How to deal with gencode gtf file

### ISSUE THREAD

**Issue by sunqiangzai** [YY-TMU/InPACT#8]
How to deal with gencode gtf file

**Comment by liuxc1995** [comment]
InPACT is designed to work with annotations from RefSeq, and currently, the GENCODE GTF file format is not compatible with InPACT.

**Comment by sunqiangzai** [comment]
Thank you, another question is `[Salmon](https://github.com/COMBINE-lab/salmon) is used to index and quantify the transcriptome, and then the usage is calculated. which fasta file is used to generate salmon index?`

**Comment by liuxc1995** [comment]
The FASTA file is generated from `merged.gtf` produced from "InPACT_transcript". Tools like gffread can be used to extract the transcript sequences from the GTF file and generate the required FASTA file.
